name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Task_1_5_1
    steps:
      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 1. ЗАПУСК ТОЛЬКО ОДНОГО ЮНИТ-ТЕСТА (TextTest) и сбор покрытия
      # Используем флаг --tests для Gradle
      - name: Run specific tests with coverage (TextTest)
        # Запускаем только тесты в классе TextTest.java
        run: ./gradlew test --tests *TextTest jacocoTestReport

      - name: List reports
        run: ls -R build/reports/jacoco

      # 2. ПУБЛИКАЦИЯ ОТЧЕТА ПОКРЫТИЯ (С фильтрацией)
      - name: Check coverage and publish
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          # Путь к сгенерированному XML-отчету
          paths: ./Task_1_5_1/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          # Устанавливаем целевое покрытие (можно снизить для временного режима)
          min-coverage-overall: 80
          min-coverage-changed-files: 80

          includes: |
            ru.nsu.ermakov.Text.Text

      - name: Generate javadoc
        run: ./gradlew javadoc

      - name: Publish javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: ./Task_1_5_1/build/docs/javadoc
          target-folder: Task_1_5_1

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: '.github/google_checks.xml'
          reporter: 'github-pr-check'